import type {
  ActiveIncidentResponse,
  AlertAuditEntry,
  Camera,
  CameraAlertSchedule,
  EmergencyContact,
  HouseholdState,
  IncidentRecord,
  SavedLocation,
  TimelineEntry,
} from "./types";

const now = "2026-05-03T18:15:00.000Z";
const incidentId = "event_cal_poly_ipaws_shelter";

export const mockHousehold: HouseholdState = {
  id: "demo-household",
  members: [
    {
      id: "guardian_1",
      name: "Alex Rivera",
      role: "guardian",
      age_category: "adult",
      status: "away",
      priority: 1,
      channels: ["telegram", "call", "sms", "email"],
      location: {
        latitude: 35.2828,
        longitude: -120.6596,
        accuracy_meters: 35,
        speed_mps: 0.4,
        label: "Downtown San Luis Obispo",
        source: "demo_seed",
        observed_at: "2026-05-03T18:09:00.000Z",
      },
      mobile_status: "safe",
      phone_e164: "+15550101001",
      telegram_chat_id: null,
    },
    {
      id: "guardian_2",
      name: "Jordan Lee",
      role: "guardian",
      age_category: "adult",
      status: "commuting",
      priority: 2,
      channels: ["telegram", "call", "email", "sms"],
      location: {
        latitude: 35.2937,
        longitude: -120.67,
        accuracy_meters: 42,
        speed_mps: 7.2,
        label: "Foothill corridor",
        source: "demo_seed",
        observed_at: "2026-05-03T18:07:00.000Z",
      },
      mobile_status: "moving",
      phone_e164: "+15550101002",
      telegram_chat_id: null,
    },
    {
      id: "child_1",
      name: "Maya Rivera",
      role: "child",
      age_category: "child",
      status: "home",
      priority: 3,
      channels: [],
      location: {
        latitude: 35.3009,
        longitude: -120.6615,
        accuracy_meters: 18,
        speed_mps: 0.1,
        label: "Home near Cal Poly campus",
        source: "demo_seed",
        observed_at: "2026-05-03T18:11:00.000Z",
      },
      mobile_status: "home",
      phone_e164: null,
      telegram_chat_id: null,
    },
  ],
  home_signal: {
    label: "Occupancy-confirmed home signal",
    occupancy_confirmed: true,
    observed_at: "2026-05-03T18:11:00.000Z",
    confidence: 0.92,
  },
  calendar_items: [
    {
      id: "calendar_pickup",
      title: "Piano lesson pickup",
      starts_at: "2026-05-03T19:00:00.000Z",
      location_label: "Downtown San Luis Obispo",
      participants: ["child_1", "guardian_1"],
    },
  ],
  demo_mode: true,
  updated_at: now,
};

export const mockActiveIncident: ActiveIncidentResponse = {
  incident: {
    id: incidentId,
    event_type: "school_shooter_shelter_in_place",
    title: "IPAWS School Shooter Shelter-in-Place Alert: Cal Poly SLO",
    description:
      "Authorities have issued a shelter-in-place alert for the Cal Poly San Luis Obispo campus. People in the affected area should move indoors, lock doors, silence phones, avoid windows, and wait for official all-clear instructions.",
    severity: "extreme",
    location_label: "Cal Poly, San Luis Obispo, CA",
    issued_at: now,
    expires_at: null,
    source_kind: "ipaws",
    source_name: "FEMA IPAWS All-Hazards Feed replay",
    source_url:
      "https://www.fema.gov/emergency-managers/practitioners/integrated-public-alert-warning-system",
    latitude: 35.3004,
    longitude: -120.6625,
    is_live: false,
    is_simulated: true,
    demo_mode: true,
    raw: {
      fixture: true,
      scenario: "cal_poly_ipaws_school_shelter",
      source_freshness: "replay",
      cap_response_type: "Shelter",
    },
  },
  camera_signal: {
    id: "camera_front_walkway",
    label: "Front walkway CCTV",
    clip_url: "/cctv/cam1.mp4",
    source: "prerecorded_demo",
    occupancy_confirmed: true,
    confidence: 0.9,
    observed_at: "2026-05-03T18:12:00.000Z",
    summary:
      "Prerecorded demo clip shows motion near the home entry and confirms occupancy context.",
  },
  classification: {
    level: "life_threatening",
    confidence: 0.86,
    rationale:
      "Extreme source severity, a child marked home near the alert area, and occupancy-confirmed camera context make this a life-threatening household coordination event.",
    classified_by: "frontend_fixture",
    source_notes: [
      "Replay data is used for judge demo mode.",
      "No real emergency dispatch or outbound message delivery is performed.",
    ],
  },
  summary:
    "A shelter-in-place alert is active around Cal Poly SLO. Maya is marked home near campus, Jordan is moving through the Foothill corridor, and GuardClaw has prepared household notification drafts.",
  action_plan: {
    id: "plan_cal_poly",
    incident_id: incidentId,
    classification: null,
    camera_signal: null,
    affected_people: [
      {
        member_id: "child_1",
        name: "Maya Rivera",
        risk_level: "home_occupant",
        reason: "Child is marked home while the alert is active.",
      },
      {
        member_id: "guardian_2",
        name: "Jordan Lee",
        risk_level: "movement",
        reason: "Member appears to be commuting near the alert area.",
      },
    ],
    notify_order: [
      {
        member_id: "guardian_1",
        name: "Alex Rivera",
        order: 1,
        channels: ["telegram"],
        reason: "Primary guardian receives the first household coordination draft.",
      },
      {
        member_id: "guardian_2",
        name: "Jordan Lee",
        order: 2,
        channels: ["call"],
        reason: "Commuting member receives a call draft because they may be moving near campus.",
      },
      {
        member_id: "child_1",
        name: "Maya Rivera",
        order: 3,
        channels: ["telegram"],
        reason: "Child is directly affected by home proximity to the alert area.",
      },
    ],
    notification_intents: [
      {
        id: "intent_alex",
        member_id: "guardian_1",
        member_name: "Alex Rivera",
        channel: "telegram",
        reason: "Life-threatening alert routed to Alex by Telegram.",
        movement_state: "away",
        priority: 1,
      },
      {
        id: "intent_jordan",
        member_id: "guardian_2",
        member_name: "Jordan Lee",
        channel: "call",
        reason: "Life-threatening alert routed to Jordan by call because they are commuting.",
        movement_state: "commuting",
        priority: 2,
      },
      {
        id: "intent_maya",
        member_id: "child_1",
        member_name: "Maya Rivera",
        channel: "telegram",
        reason: "Life-threatening alert routed to Maya because she is marked home.",
        movement_state: "home",
        priority: 3,
      },
    ],
    recommended_actions: [
      {
        id: "action_route",
        label: "Route household alert",
        detail: "Life-threatening alerts immediately notify every household member.",
        priority: 1,
      },
      {
        id: "action_confirm",
        label: "Confirm highest-risk members",
        detail: "Confirm Maya's location and ask Jordan to avoid campus routes.",
        priority: 2,
      },
      {
        id: "action_source",
        label: "Keep source labels explicit",
        detail: "Show this as replay fixture data for the hackathon judge demo.",
        priority: 3,
      },
    ],
    rationale:
      "GuardClaw classified this alert as life threatening. It routes to every household member, prioritizes Maya at home and Jordan in motion, and logs message drafts instead of sending real outbound notifications.",
    outbound_messages: [
      {
        id: "message_alex",
        incident_id: incidentId,
        recipient_id: "guardian_1",
        recipient_name: "Alex Rivera",
        channel: "telegram",
        status: "sent_stub",
        subject: "GuardClaw life threatening alert: Cal Poly shelter in place",
        body: "Maya is marked home near the Cal Poly alert area. Confirm status, keep routes away from campus, and monitor the household timeline.",
        created_at: now,
        demo_mode: true,
        generated_by: "frontend_fixture",
      },
      {
        id: "message_jordan",
        incident_id: incidentId,
        recipient_id: "guardian_2",
        recipient_name: "Jordan Lee",
        channel: "call",
        status: "sent_stub",
        subject: "GuardClaw call draft: avoid Cal Poly area",
        body: "You appear to be moving near Foothill. Avoid campus routes and confirm whether you are safe.",
        created_at: now,
        demo_mode: true,
        generated_by: "frontend_fixture",
      },
    ],
    created_at: now,
    demo_mode: true,
    generated_by: "frontend_fixture",
  },
  demo_mode: true,
};

export const mockTimeline: TimelineEntry[] = [
  {
    id: "timeline_created",
    incident_id: incidentId,
    kind: "incident_created",
    title: "Simulated incident created",
    detail:
      "IPAWS School Shooter Shelter-in-Place Alert: Cal Poly SLO was ingested from FEMA IPAWS All-Hazards Feed replay.",
    actor: "guardclaw",
    created_at: "2026-05-03T18:15:00.000Z",
    acknowledged_at: null,
    metadata: { source: "ipaws", is_live: false, is_simulated: true },
    demo_mode: true,
  },
  {
    id: "timeline_camera",
    incident_id: incidentId,
    kind: "camera_signal_ingested",
    title: "Front walkway CCTV attached",
    detail:
      "Prerecorded demo clip shows motion near the home entry and confirms occupancy context.",
    actor: "guardclaw",
    created_at: "2026-05-03T18:15:04.000Z",
    acknowledged_at: null,
    metadata: {},
    demo_mode: true,
  },
  {
    id: "timeline_classified",
    incident_id: incidentId,
    kind: "alert_classified",
    title: "Alert classified as life threatening",
    detail:
      "Extreme source severity plus household location and occupancy context require household-wide notification drafts.",
    actor: "guardclaw",
    created_at: "2026-05-03T18:15:08.000Z",
    acknowledged_at: null,
    metadata: { confidence: 0.86 },
    demo_mode: true,
  },
  {
    id: "timeline_plan",
    incident_id: incidentId,
    kind: "plan_created",
    title: "Action plan generated",
    detail:
      "Notify every household member, confirm Maya first, and route Jordan away from campus.",
    actor: "guardclaw",
    created_at: "2026-05-03T18:15:12.000Z",
    acknowledged_at: null,
    metadata: { generated_by: "frontend_fixture" },
    demo_mode: true,
  },
  {
    id: "message_alex",
    incident_id: incidentId,
    kind: "outbound_message",
    title: "Telegram draft logged for Alex Rivera",
    detail:
      "Frontend-only demo mode: GuardClaw generated a message draft and logged it instead of sending a real external message.",
    actor: "guardclaw",
    created_at: "2026-05-03T18:15:16.000Z",
    acknowledged_at: null,
    metadata: { channel: "telegram", status: "sent_stub" },
    demo_mode: true,
  },
];

export const mockAuditLog: AlertAuditEntry[] = [
  {
    id: "audit_cal_poly",
    source_kind: "ipaws",
    source_id: incidentId,
    event_type: "school_shooter_shelter_in_place",
    severity: "extreme",
    title: "IPAWS School Shooter Shelter-in-Place Alert: Cal Poly SLO",
    ingested_at: now,
    pipeline_triggered: true,
  },
  {
    id: "audit_nws",
    source_kind: "nws",
    source_id: "nws_replay_high_wind",
    event_type: "weather_alert",
    severity: "high",
    title: "NWS severe weather alert replay",
    ingested_at: "2026-05-03T17:44:00.000Z",
    pipeline_triggered: true,
  },
  {
    id: "audit_usgs",
    source_kind: "usgs",
    source_id: "usgs_slo_fixture",
    event_type: "earthquake",
    severity: "moderate",
    title: "M 3.8 earthquake near San Luis Obispo",
    ingested_at: "2026-05-03T16:55:00.000Z",
    pipeline_triggered: false,
  },
];

export const mockIncidents: IncidentRecord[] = [
  {
    id: "incident_cal_poly",
    event_id: incidentId,
    summary: mockActiveIncident.summary ?? "",
    classification_level: "life_threatening",
    status: "active",
    affected_members: [
      { member_id: "child_1", name: "Maya Rivera", risk_level: "home_occupant" },
      { member_id: "guardian_2", name: "Jordan Lee", risk_level: "movement" },
    ],
    source_kind: "ipaws",
    severity: "extreme",
    location_label: "Cal Poly, San Luis Obispo, CA",
    created_at: now,
  },
  {
    id: "incident_weather",
    event_id: "event_nws_wind",
    summary:
      "Replay severe weather alert near San Luis Obispo. Guardians were notified and source labeling stayed explicit.",
    classification_level: "major",
    status: "resolved",
    affected_members: [{ member_id: "guardian_2", name: "Jordan Lee", risk_level: "movement" }],
    source_kind: "nws",
    severity: "high",
    location_label: "San Luis Obispo, CA",
    created_at: "2026-05-03T17:44:00.000Z",
  },
];

export const mockSavedLocations: SavedLocation[] = [
  {
    id: "saved_home",
    family_id: "demo-household",
    member_id: "child_1",
    label: "home",
    lat: 35.3009,
    lng: -120.6615,
    created_at: "2026-05-03T17:30:00.000Z",
  },
  {
    id: "saved_school",
    family_id: "demo-household",
    member_id: "child_1",
    label: "school",
    lat: 35.3004,
    lng: -120.6625,
    created_at: "2026-05-03T17:31:00.000Z",
  },
];

export const mockEmergencyContacts: EmergencyContact[] = [
  {
    id: "ec_neighbor",
    family_id: "demo-household",
    name: "Sam Patel",
    phone_e164: "+15550102001",
    email: "sam@example.com",
    relationship: "neighbor",
    created_at: "2026-05-03T17:20:00.000Z",
  },
  {
    id: "ec_grandparent",
    family_id: "demo-household",
    name: "Elena Rivera",
    phone_e164: "+15550102002",
    email: "elena@example.com",
    relationship: "grandparent",
    created_at: "2026-05-03T17:22:00.000Z",
  },
];

export const mockCameras: Camera[] = [
  {
    id: "camera_1",
    family_id: "demo-household",
    label: "Front Walkway",
    location_label: "Home near Cal Poly campus",
    stream_url: "cam1.mp4",
    enabled: true,
    created_at: "2026-05-03T16:00:00.000Z",
    updated_at: now,
  },
  {
    id: "camera_2",
    family_id: "demo-household",
    label: "Driveway",
    location_label: "Foothill approach",
    stream_url: "cam2.mp4",
    enabled: true,
    created_at: "2026-05-03T16:00:00.000Z",
    updated_at: now,
  },
];

export const mockCameraSchedules: CameraAlertSchedule[] = [
  {
    id: "schedule_evening",
    camera_id: "camera_1",
    family_id: "demo-household",
    day_of_week: 0,
    start_time: "18:00",
    end_time: "23:00",
    enabled: true,
    created_at: "2026-05-03T16:00:00.000Z",
  },
];
